Superstore::Type.register(:array,          Superstore::Types::ArrayType)
Superstore::Type.register(:boolean,        Superstore::Types::BooleanType)
Superstore::Type.register(:date,           Superstore::Types::DateType)
Superstore::Type.register(:float,          Superstore::Types::FloatType)
Superstore::Type.register(:integer,        Superstore::Types::IntegerType)
Superstore::Type.register(:json,           Superstore::Types::JsonType)
Superstore::Type.register(:time,           Superstore::Types::TimeType)
Superstore::Type.register(:string,         Superstore::Types::StringType)
