name: Ruby
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby: [ '2.5.8', '3.1' ]
    env:
      BUNDLE_GITHUB__COM: "${{ secrets.BUNDLE_GITHUB__COM }}"
      BUNDLE_GEMS__CONTRIBSYS__COM: "${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}"
      BUNDLE_WITHOUT: "development:production:qa:sandbox"
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    services:
      postgres:
        image: postgres:12.8
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: runner
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Install Ruby, bundler and the bundle
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
    - name: Publish code coverage
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: paambaati/codeclimate-action@v3.0.0
